services:
  product-service:
    build: ./product-service
    container_name: cloudpulse-product-service
    ports:
      - "3001:3001"

  user-service:
    build: ./user-service
    container_name: cloudpulse-user-service
    ports:
      - "3002:3002"

  order-service:
    build: ./order-service
    container_name: cloudpulse-order-service
    ports:
      - "3003:3003"
