apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cloudpulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 921040036993.dkr.ecr.us-west-1.amazonaws.com/cloudpulse:user-latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: mysql

            - name: DB_USER
              value: cloudpulse

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: DB_NAME
              value: cloudpulse

            - name: DB_PORT
              value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cloudpulse
spec:
  selector:
    app: user-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
