name: CloudPulse CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Product Service dependencies
        working-directory: product-service
        run: npm ci

      - name: Install User Service dependencies
        working-directory: user-service
        run: npm ci

      - name: Install Order Service dependencies
        working-directory: order-service
        run: npm ci

      - name: Build CloudPulse services
        run: docker compose build

      - name: Start CloudPulse services
        run: docker compose up -d

      - name: Wait for services
        run: |
          echo "Waiting for Product Service..."
          for i in {1..30}; do
            if curl -f http://localhost:3001/health; then
              echo "Product Service is ready"
              break
            fi
            sleep 2
          done

          echo "Waiting for User Service..."
          for i in {1..30}; do
            if curl -f http://localhost:3002/health; then
              echo "User Service is ready"
              break
            fi
            sleep 2
          done

          echo "Waiting for Order Service..."
          for i in {1..30}; do
            if curl -f http://localhost:3003/health; then
              echo "Order Service is ready"
              break
            fi
            sleep 2
          done

      - name: Show running containers
        run: docker compose ps

      - name: Run Product Service tests
        working-directory: product-service
        run: npm test

      - name: Run User Service tests
        working-directory: user-service
        run: npm test

      - name: Run Order Service tests
        working-directory: order-service
        run: npm test

      - name: Show service logs on failure
        if: failure()
        run: docker compose logs

      - name: Stop CloudPulse services
        if: always()
        run: docker compose down -v

      # AWS authentication using GitHub OIDC

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::921040036993:role/CloudPulseGitHubActionsRole
          aws-region: us-west-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Product Service image
      - name: Build Product Service Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/cloudpulse:product-${{ github.sha }} ./product-service
          docker tag ${{ steps.login-ecr.outputs.registry }}/cloudpulse:product-${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/cloudpulse:product-latest

      # Push Product Service image
      - name: Push Product Service Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/cloudpulse:product-${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/cloudpulse:product-latest

      # Build User Service image
      - name: Build User Service Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/cloudpulse:user-${{ github.sha }} ./user-service
          docker tag ${{ steps.login-ecr.outputs.registry }}/cloudpulse:user-${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/cloudpulse:user-latest

      # Push User Service image
      - name: Push User Service Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/cloudpulse:user-${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/cloudpulse:user-latest

      # Build Order Service image
      - name: Build Order Service Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/cloudpulse:order-${{ github.sha }} ./order-service
          docker tag ${{ steps.login-ecr.outputs.registry }}/cloudpulse:order-${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/cloudpulse:order-latest

      # Push Order Service image
      - name: Push Order Service Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/cloudpulse:order-${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/cloudpulse:order-latest
